### ISSUE TITLE
Error characteristic not found during start_notify

### ISSUE THREAD

**Issue by hofmannu** [gmanic/daly_bms_bt#6]
```
INFO     [daly_bms_bluetooth.py:46] Bluetooth connecting...
INFO     [daly_bms_bluetooth.py:52] Bluetooth connected
ERROR    [base_events.py:1820] Task exception was never retrieved
future: <Task finished name='Task-1' coro=<main() done, defined at <>Code/battery/bluetooth/daly_bms_bt/daly_bms_bt.py:123> exception=BleakCharacteristicNotFoundError('Characteristic 17 was not found!')>
Traceback (most recent call last):
  File "<>/Code/battery/bluetooth/daly_bms_bt/daly_bms_bt.py", line 130, in main
    await con.connect()
  File "<>/Code/battery/bluetooth/daly_bms_bt/daly_bms_bt.py", line 104, in connect
    await self.bt_bms.connect()
  File "<>/Code/battery/bluetooth/daly_bms_bt/modules/daly_bms_bluetooth.py", line 53, in connect
    await self.client.start_notify(17, self._notification_callback)
  File "<>/Code/battery/bluetooth/battery-test/lib/python3.12/site-packages/bleak/__init__.py", line 832, in start_notify
    raise BleakCharacteristicNotFoundError(char_specifier)
bleak.exc.BleakCharacteristicNotFoundError: Characteristic 17 was not found!
```

I think this is somehow linked to the start notify call. If I list the characteristics of the client, I cannot find 17 but only 

```
26 --> 02f00000-0000-0000-0000-00000000ff02 (Handle: 26): Unknown
33 --> 02f00000-0000-0000-0000-00000000ff04 (Handle: 33): Unknown
36 --> 02f00000-0000-0000-0000-00000000ff05 (Handle: 36): Unknown
31 --> 02f00000-0000-0000-0000-00000000ff01 (Handle: 31): Unknown
29 --> 02f00000-0000-0000-0000-00000000ff00 (Handle: 29): Unknown
24 --> 02f00000-0000-0000-0000-00000000ff03 (Handle: 24): Unknown
11 --> 00002a05-0000-1000-8000-00805f9b34fb (Handle: 11): Service Changed
19 --> 0000fff2-0000-1000-8000-00805f9b34fb (Handle: 19): Vendor specific
15 --> 0000fff1-0000-1000-8000-00805f9b34fb (Handle: 15): Vendor specific
```

have you ever encountered a configuration like this? any clue which handle I should try instead? thanks a lot in advance for your help

**Comment by gmanic** [comment]
No, I haven't seen something like that.

&TLDR;
To be honest, I stopped working on this repo.

For one, I dropped the daly and changed to JBD.
The other reason is, that I changed my setup to have both local BMS connect via UART to my Victron setup. I use a simple hardware switch to change from UART->Victron to Bluetooth. BT is used only, if I need to connect with some BMS-App to change basic parameters. And this happens just like once every xx months - if at all (because all is working fine :) ).

That's the reason for not investigating further.
